### ISSUE TITLE
Use one `.d.ts` file for type definitions

### ISSUE THREAD

**Issue by Josh-Cena** [TheNightmareX/berry-orm#2]
有点不大明白为啥一个类型用一个文件定义 orz 其实可以用一个 `types.d.ts` 定义所有需要复用的类型，然后就可以在其他文件里访问了，甚至不需要 `import`

（还有，Prettier 都有了，ESLint 不考虑一下嘛）

同高中狗，加油啊老哥

**Comment by TheNightmareX** [comment]
是为了遵循单一职责原则哦~简单说就是坚持每个文件只导出一个内容。

如果你仔细阅读代码，你会发现 Berry ORM 对类型十分注重，部分类型具有一定复杂度，全部放在一个文件中会导致阅读困难，此外，我把类型看作是和其他代码地位相同的，所以我更倾向于对于类型也同样遵循单一职责原则，同样进行导入。

单一职责原则主要优点有：

- 阅读一个内容时，不会受到其他内容的干扰，
- 由于一个文件只有一个内容，可以大量减少合并冲突
- 可以通过文件名来快速定位要查找内容的位置

**Comment by Josh-Cena** [comment]
噢噢，了解了
因为我接触的 TS 库基本都是一个 ambient module 解决 typing 的问题，有时候会有几十个 types，不过用 SRP 也阔以
ESLint 会考虑嘛（每日一问）这个的配置的水要比 Prettier 深

**Comment by TheNightmareX** [comment]
ESLint 马上就会加上的啦

我目前其实还是更倾向于把类型显式导入进来啦，可能只是个人习惯的问题……

**Comment by TheNightmareX** [comment]
> ESLint 马上就会加上的啦

可能会晚点了，因为还没有自己配置过eslint……目前来看也不太会有其他人向这个仓库提交代码 :-(

**Comment by Josh-Cena** [comment]
我可以帮忙的啦_(:з」∠)_我先发个 PR，然后我们可以讨论下具体的 style 问题

**Comment by Josh-Cena** [comment]
Fixed in #3. Closing
